name: github-ci

on: [push, pull_request]

jobs:
  dependencies:
    name: vendor
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - uses: actions/checkout@v2
      - name: go mod vendor
        run: |
          go mod vendor
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.29
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: go test
      run: |
        go test -race -v -coverprofile .coverage.txt ./...
